---
title: "Project 4 - Collaborative Filtering"
author: "Team 10"
date: "4/18/2018"
output: pdf_document
---

## Step 0: Load the packages, specify directories
```{r}
# Packages that will be used
packages.used <- c("reshape2", "Hmisc")
# Check packages that need to be installed
packages.needed <- setdiff(packages.used, 
                           intersect(installed.packages()[,1], 
                                     packages.used))
# Install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE,
                   repos='http://cran.us.r-project.org')
}
# Load libraries  
library("Hmisc","reshape2")

# Set working directory to the doc folder 
#setwd("~/GitHub/Spring2018-Project4-group-10/doc")
```

## Step 1: Load and process the data  
```{r}
#train1 <- read.csv("../data/MS_sample/data_train.csv", header=TRUE)
#test1 <- read.csv("../data/MS_sample/data_test.csv", header=TRUE)
train2 <- read.csv("../data/eachmovie_sample/data_train.csv", header=TRUE)
test2 <- read.csv("../data/eachmovie_sample/data_test.csv", header=TRUE)

#library("reshape2")
df.train2 <- dcast(train2, User~Movie, value.var = "Score", fill = NA)
df.test2 <- dcast(test2, User~Movie, value.var = "Score", fill = NA)
rownames(df.train2) <- df.train2[,1]
rownames(df.test2) <- df.test2[,1]
df.train2 <- df.train2[,-1]
df.test2 <- df.test2[,-1]
#dim(df.train2) 
#df.train2[1:6,1:9]
```
## Step 2: Implement Algorithm
### Model-based Algorithm - Cluster Models
#### Stage  
```{r}
run.CM.cv <- FALSE
run.CM.pars <- FALSE
run.CM.est <- FALSE

source("../lib/ClusterModel.R")
### cluster.cv -- Perfom K-Fold Cross-Validation
### cluster.em -- Learn Parameters Using EM Algorithm
### cluster.score -- Compute Score Estimation 
### cluster.pi -- Compute Responsibilities  
```

#### Choose C by 5-Fold Cross-Validation  
```{r}
CM.C.list <- c(seq(3,13, by=2))

if(run.CM.cv){
  CM.error.validation <- cluster.cv(df.train2, CM.C.list)
  save(CM.error.validation, file = paste0("../output/CM.error.validation.RData"))
}else{
  load("../output/CM.error.validation.RData")
}

#library("Hmisc")
CM.error.cv <- colMeans(CM.error.validation)
CM.error.cv.sd <- apply(CM.error.validation, 2, sd)/sqrt(nrow(CM.error.validation))
CM.c.min <- which.min(CM.error.cv)
CM.error.cv.lbound <- CM.error.cv[CM.c.min] - CM.error.cv.sd[CM.c.min]
CM.error.cv.ubound <- CM.error.cv[CM.c.min] + CM.error.cv.sd[CM.c.min]
plot(CM.C.list, CM.error.cv, main = "5-Fold Cross-Validation",
     xlab = "Number of Classes", ylab = "Prediction Error", 
     ylim = c(0.98,1.05), xaxt = "n", 
     type = "l", col="steelblue2")
axis(1, at = CM.C.list, labels = CM.C.list)
errbar(CM.C.list, CM.error.cv, 
       CM.error.cv+CM.error.cv.sd, CM.error.cv-CM.error.cv.sd, 
       add = TRUE, errbar.col = gray(0.4), lwd = 0.5)
points(CM.C.list, CM.error.cv, col="steelblue2",pch = 19)
abline(h=CM.error.cv.lbound, col=gray(0.4), lty=2)
abline(h=CM.error.cv.ubound, col=gray(0.4), lty=2)
dev.copy2pdf(file ="../figs/CM.CrossValidation.pdf")
CM.C.best <- CM.C.list[(CM.error.cv>CM.error.cv.lbound) 
                       & (CM.error.cv<CM.error.cv.ubound)][1]
print(paste0("The Best number of classes is ", CM.C.best))  
```
#### Learn Parameters Using the C Chosen 
```{r}
if(run.CM.pars){
  CM.pars <- cluster.em(df.train2, C.best, 0.05)
  save(CM.pars, file = paste0("../output/CM.pars.RData"))
}else{
  load("../output/CM.pars.RData")
}
```

####  Compute Score Estimation & Test Error  
```{r}
if(run.CM.est){
  CM.est <- cluster.score(df.train2, CM.pars)
  save(CM.est, file = paste0("../output/CM.est.RData"))
}else{
  load("../output/CM.est.RData")
}

CM.error.test <- sum(abs(CM.est-df.test2),na.rm = T)/ sum(!is.na(CM.est-df.test2))
print(paste0("The test error of the cluster model is ", round(CM.error.test,4),"."))
```
### Memory-based Algorithm  
